import NavBar from "@/components/dashboard/navbar/NavBar"
import SideBar from "@/components/dashboard/sidebar/SideBar"
import '../[locale]/globals.css'
import Footer from "@/components/dashboard/footer/Footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="bg-Bgdash text-white">
        <div className="flex flex-row ">

        <div className="w-1/5 bg-Bgdash-foreground p-5 m-5 rounded-[8px] h-vh  ">
          <SideBar/>
        </div>
        <div className="w-4/5  bg-Bgdash p-5">
          <NavBar/>
        
          <div className=" bg-Bgdash-foreground p-5 mt-5 rounded-[8px]">

            {children}
          </div>
            <Footer/>
        </div>
        </div>
      </body>
    </html>
  )
}
